name: Setup
description: Sets up the Flutter environment

inputs:
  pub-cache:
    description: "The name of the pub cache variable"
    required: false
    default: app

runs:
  using: composite
  steps:
    - name: 📦 Checkout the repo
      uses: actions/checkout@v4

    - name: 🔢 Set up version from tags
      id: set-version
      if: startsWith(github.ref, 'refs/tags')
      shell: bash
      run: |
        BASE_VERSION="${GITHUB_REF#refs/tags/v}"
        UNIXTIME=$(date +%s)
        VERSION="${BASE_VERSION}+${UNIXTIME}"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        sed -i "s/^version: .*/version: ${VERSION}/" pubspec.yaml
        echo "Version set to $VERSION"

    - name: 🚂 Setup Flutter via FVM
      uses: kuhnroyal/flutter-fvm-config-action/setup@v3

    - name: 📤 Restore Pub modules
      id: cache-pub-restore
      uses: actions/cache/restore@v4
      with:
        path: /home/runner/.pub-cache
        key: ${{ runner.os }}-pub-${{ inputs.pub-cache }}-${{ hashFiles('pubspec.lock') }}

    - name: 👷 Install Dependencies
      shell: bash
      run: |
        echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
        flutter config --no-cli-animations --no-analytics
        flutter pub get

    - name: ⏲️ Run build runner
      shell: bash
      run: |
        dart run build_runner build --delete-conflicting-outputs --release

    - name: 📥 Save Pub modules
      if: steps.cache-pub-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: /home/runner/.pub-cache
        key: ${{ steps.cache-pub-restore.outputs.cache-primary-key }}
