name: notex
description: "Simple notes"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: ^3.7.2

# переменные
riverpod_version: &riverpod_version ^2.6.1
dart_mappable_version: &dart_mappable_version ^4.5.0
drift_version: &drift_version ^2.26.1

dependencies:
  flutter:
    sdk: flutter

  # localizations
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  timeago: ^3.7.1

  faker: ^2.2.0

  # state management + di
  riverpod: *riverpod_version
  flutter_riverpod: *riverpod_version

  # storage + memory
  drift: *drift_version
  drift_flutter: ^0.2.4
  sqlite3: ^2.7.5
  sqlite3_flutter_libs: ^0.5.32
  shared_preferences: ^2.5.3

  # utils
  dart_mappable: *dart_mappable_version
  collection: any
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  # testing
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4
  golden_toolkit: ^0.15.0
  fake_async: ^1.3.2

  # builders
  drift_dev: *drift_version
  dart_mappable_builder: *dart_mappable_version
  build_runner: any

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
