name: notex
description: "Simple notes"
publish_to: "none"

version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # localizations
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  timeago: ^3.7.1

  faker: ^2.2.0

  # state management + di
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1

  # storage + memory
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  sqlite3: ^2.7.5
  sqlite3_flutter_libs: ^0.5.32
  shared_preferences: ^2.5.3

  # utils
  dart_mappable: ^4.5.0
  collection: any
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  # testing
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4
  golden_toolkit: ^0.15.0
  fake_async: ^1.3.2

  # builders
  drift_dev: ^2.26.1
  dart_mappable_builder: ^4.5.0
  build_runner: any

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
